### ISSUE TITLE
Feature Request, tab for environments

### ISSUE THREAD

**Issue by cellcore** [skx/puppet-summary#54]
In the report there is "environment: env_name"

Would it be possible to have the main page create tabs based on the env_name? You could click on an env_name to show all the nodes in that environment. Or just a drop down to separate nodes in different environments. 

Thanks!

**Comment by skx** [comment]
This isn't a bad feature-suggestion, but it will be harder than it should be because we currently don't parse/store the environment in the database when we parse incoming submissions.

If we want to start doing that we'll have a breaking-change post-upgrade, where old reports will disappear.

It wouldn't be a difficult change to add, I suspect, but I think I wouldn't implement it myself.  Just review any pull-request which was contributed.
