### ISSUE TITLE
Performance issues in initial display

### ISSUE THREAD

**Issue by tnail** [skx/puppet-summary#61]
We're running the latest revision of puppet-summary on RHEL7.6, front-ended with Apache and experiencing really poor performance from the web front-end. Page load times are on the order of 90+ seconds for 499 hosts and we're pruning the database to 14 days of retention. Are there any tips for gaining more performance out of this application?

**Comment by skx** [comment]
The biggest report of usage I've received so far was in #42 which mentioned a reasonable number of reports.  (Assuming 14k reports/day, and hourly runs I'm gonna guess that covers about 50 hosts.)

I guess I'd try to start by seeing how you're setup, I'd assume the summary-server is located upon your puppet-master, because that's the simplest way to deploy it.  If so it might be interesting to see if moving it externally helped.  To be honest you could just use `rsync` to clone the reports, sqlite file, and see how it performed without receiving updates.

Otherwise I'd ask if the host is I/O-bound, or CPU-starved.  If so add more.

As things stand the front-page does do a fair number of queries to count the hosts, and get their most recent state.  But it doesn't seem like any of them should be _too_ heavyweight.

I suspect pruning won't necessarily improve performance, but that would also be my first suggestion just to confirm.  (The reason I say that is that the displays mostly only touch the SQLite database - the actual on-disk reports are only used when you view a particular run.)
