### ISSUE TITLE
debian 11 - go install - nothing happens

### ISSUE THREAD

**Issue by unclesam87** [skx/puppet-summary#86]
hey, 
i just spinned up an debian 11 puppet and tried to install ur plugin,
as i run go install nothing happens (first try it crashed bc it missed gcc compiler:
`cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH`
installed them per apt install gcc, and then it seems to run without any output.
as i try to start puppet-summary - i get an command not found.

here my cookbook for ur plugin:

`download go:
 wget https://golang.org/dl/go1.19.3.linux-amd64.tar.gz
 tar -zxvf go1.19.3.linux-amd64.tar.gz -C /usr/local/
 nano .profile
add content at the end of file:
export PATH=$PATH:/usr/local/go/bin
to test:
 go version
download webUI
 git clone https://github.com/skx/puppet-summary
 puppet-summary 
 go install `

**Comment by skx** [comment]
You can build the program:

     go build .

You can install the program - as you did:
 
     go install .

Your problem is _probably_ that the install has placed the binary in a directory not on your PATH `$GOPATH/bin`

I suggest you look at the value of "GOPATH", by running:

     go env

And then look beneath that.

Closing as not an issue with this software anyway, it's a `go` toolchain and/or local config issue.
